### ISSUE TITLE
US 02.01.01 - Add recipe entry

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#11]
**User story: As a meal planner, I want to add a recipe, with title, preparation time, number of servings, recipe category, comments, photograph, and list of ingredients.**

Similar to #5, we need to add functionality to add recipes to our recipe list. We will have a dialog box for this, and the recipe entry list should have the following fields:

- Title of recipe
- Preparation time of recipe
- Number of servings
- Category
- Comments
- Photograph of recipe
- List of ingredients

_Acceptance Criteria_
- [x] We need a button on our recipe screen that brings us to an "Add recipe entry" dialog box
- [x] On the recipe entry box, we require a string input for title and comments
- [x] On the recipe entry box, we require a dropdown for categories. The user can add and remove categories in that same dropdown
- [x] On the recipe entry box, we require numeric input for number of servings
- [x] On the recipe entry box, we require a time input for preparation time
- [x] On the recipe entry box, we require some sort of image-uploading portal
- [x] On the recipe entry box, we require some dropdown where we can add an unlimited amount of ingredients to this recipe. Refer to #12 
- [x] We need to error check for incorrect input
- [x] A submit entry button must be available that adds the recipe to the recipes listview
- [x] A cancel button must be available so the user can cancel their entry
- [x] Each additional entry should be stored in our remote Firebase database

**Comment by HiltonTR** [comment]
Cancel is tapping out of the fragment area or using physical back button

**Comment by JakobLau9** [comment]
- [x] Added JUnit Testing

**Comment by HiltonTR** [comment]
Waiting on Kody to finish the recipe ingredients class
