### ISSUE TITLE
US 02.02.01 - Add ingredient to recipe

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#12]
**User story: As a meal planner, I want to add an ingredient to a recipe, with a brief description, amount, unit, and ingredient category.**

In the add recipe screen #11, we need to add a dropdown that detects the ingredients in our ingredients list, and is able to add any amount of these ingredients to the recipe entry. This should maintain a viewable list where we can see which current ingredients are added. 

_Acceptance Criteria_

- [x] Within the add recipe entry dialog, we need a dropdown that clearly indicates for the user to select any number of ingredients
- [x] Once clicked, the dropdown should show every single ingredient currently present in our ingredient list
- [x] The user should be able to select an ingredient from this list and add it to the recipe
- [x] The user should also be able to create a new ingredient from this dialog box in a similar manner as #5 
- [x] Refer to #13 for additional features in this dropdown
- [x] Once the ingredient is added, it should show up as a list within the recipe entry page. This will be scrollable if many ingredients are added

**Comment by JakobLau9** [comment]
- [x] Added JUnit Testing
