### ISSUE TITLE
US 01.01.01 - Add ingredient items

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#5]
**User story: As a meal planner, I want to add an ingredient, with a brief description, best before date, location, amount, unit, and ingredient category.**

We require functionality to add ingredients to our app. 
Ingredients should have the following attributes:
- description
- best before date
- location
- amount
- unit
- category

_Acceptance Criteria_
- [x] We need a button on our ingredients screen that brings us to an "Add food entry" dialog box
- [x] On the food entry box, we require a string input for description, location
- [x] On the food entry box, we require a date input for the best-before date
- [x] On the food entry box, we require a dropdown with preselected units
- [x] On the food entry box, we require some sort of image-uploading portal
- [x] On the food entry box, we require a category dropdown. The user can add and remove categories in that same dropdown
- [x] We need to error check for incorrect input
- [x] A submit entry button must be available that adds the ingredient to the ingredients listview
- [x] A cancel button must be available so the user can cancel their entry
- [x] Each additional entry should be stored in our remote Firebase database

**Comment by JakobLau9** [comment]
- [x] Added JUnit Testing
