### ISSUE TITLE
US 01.02.01 - Ingredient View

### ISSUE THREAD

**Issue by 5yph** [CMPUT301F22T11/Mealy#6]
**User story: As a meal planner, I want to view an ingredient and its details.**

We need to display all the information of the ingredients created in #5. Details of the ingredients should include the description, best-before date, location, amount, unit, and category.  

_Acceptance Criteria_
- [ ] View button that brings us to view dialog box, from #9
- [ ] View dialog box that contains all the details in text format
- [ ] View box is updated when the ingredient is edited
- [ ] Tapping outside the popup should close the view

**Comment by JakobLau9** [comment]
- [x] Added JUnit Testing
